### ISSUE TITLE
GC stats

### ISSUE THREAD

**Issue by dnlup** [dnlup/doc#5]
Consider adding garbage collection metrics.

**Comment by acheronfail** [comment]
The `PerformanceObserver` API could help out here: https://github.com/nodejs/diagnostics/blob/master/documentation/memory/step3/using_gc_traces.md

**Comment by dnlup** [comment]
Thank you @acheronfail , this is a great suggestion. I definitely wanted to use available Node API and not a userland package for this, I missed that part of the documentation.
